services:
  db:
    image: postgres:18.4-alpine
    hostname: ${DATABASE_HOST}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data_tc_website:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=driftrecall

volumes:
  postgres_data_driftrecall:
